Repository dfir-iris/iris-web, pull requests merged in 2021-12, with the labels that each got.

#9 add ATT&CK tactics
  source/app/post_init.py
Labels: enhancement

#12 [#11][FIX] Showcase in readme
  README.md
  img/demo_timeline.png
Labels: documentation

#13 Updates of README and addition of MITRE
  README.md
  img/demo_timeline.png
  source/app/post_init.py
Labels: documentation

#4 [#2][FIX] Fixed duplicated path to add customer
  source/app/blueprints/dashboard/dashboard_routes.py
  source/app/blueprints/manage/manage_customers_routes.py
  source/app/static/assets/js/iris/dashboard.js
  source/app/static/assets/js/iris/manage_customers.js
Labels: invalid

#10 I5 tm tooltip
  source/app/static/assets/js/iris/case.timeline.js
  source/app/static/assets/js/iris/common.js
Labels: bug

#15 [UPD] add a per-column filtering field in the case view
  source/app/blueprints/case/templates/case_assets.html
  source/app/blueprints/case/templates/case_ioc.html
  source/app/blueprints/case/templates/case_rfile.html
  source/app/blueprints/case/templates/case_tasks.html
  source/app/static/assets/js/iris/case.asset.js
  source/app/static/assets/js/iris/case.ioc.js
  source/app/static/assets/js/iris/case.rfiles.js
  source/app/static/assets/js/iris/case.tasks.js
  source/app/static/assets/js/iris/datatablesUtils.js
Labels: enhancement
