Repository dfir-iris/iris-web, pull requests merged in 2022-05, with the labels that each got.

#101 [FIX][ADD] Multiple fixes and added custom Asset Icon handling
  .gitignore
  docker-compose.yml
  docker/webApp/Dockerfile
  source/app/alembic/versions/ff917e2ab02e_changed_the_asset_type_table_for_custom_.py
  source/app/blueprints/case/case_graphs_routes.py
  source/app/blueprints/case/case_timeline_routes.py
  source/app/blueprints/case/templates/modal_add_case_asset.html
  source/app/blueprints/case/templates/modal_add_case_event.html
  source/app/blueprints/login/templates/login.html
  source/app/blueprints/manage/manage_assets_type_routes.py
  source/app/blueprints/manage/templates/manage_objects.html
  source/app/blueprints/manage/templates/modal_add_asset_type.html
  source/app/configuration.py
  source/app/datamgmt/case/case_events_db.py
  source/app/forms.py
  source/app/models/models.py
  source/app/post_init.py
  source/app/static/assets/css/login/css.css
  source/app/static/assets/js/iris/manage_objects.js
  source/app/util.py
Labels: enhancement

#107 Modification history in timeline
  source/app/alembic/versions/ca93d4b54571_add_created_by_in_events.py
  source/app/blueprints/case/case_timeline_routes.py
  source/app/blueprints/case/templates/case_timeline.html
  source/app/blueprints/case/templates/modal_add_case_event.html
  source/app/blueprints/context/context.py
  source/app/models/cases.py
  source/app/schema/marshables.py
  source/app/static/assets/css/atlantis.css
  source/app/static/assets/js/iris/case.timeline.js
  source/app/util.py
Labels: enhancement

#110 [FR] Implementation of bulk editing of multiple events
  source/app/blueprints/case/templates/case_timeline.html
  source/app/static/assets/css/atlantis.css
  source/app/static/assets/js/iris/case.timeline.js
Labels: enhancement

#112 [FIX] Context switch button doesn't load cases
  source/app/templates/includes/navigation.html
  source/app/templates/includes/navigation_ext.html
Labels: bug

#113 Bugfixes v1.4.3 -> v1.4.4
  .bumpversion.cfg
  source/app/blueprints/case/templates/case_notes.html
  source/app/blueprints/case/templates/case_tasks.html
  source/app/blueprints/case/templates/case_timeline.html
  source/app/blueprints/dashboard/templates/index.html
  source/app/configuration.py
  source/app/iris_engine/updater/updater.py
  source/app/static/assets/css/atlantis.css
  source/app/static/assets/js/iris/case.timeline.js
  source/app/templates/includes/navigation.html
  source/app/templates/includes/navigation_ext.html
  source/app/templates/includes/quick-sidebar.html
  source/scripts/iris_updater.sh
  source/setup.py
Labels: bug

#117 I116 - Password policy
  source/app/alembic/versions/cd519d2d24df_password_policy_edition.py
  source/app/blueprints/manage/manage_users.py
  source/app/blueprints/manage/templates/manage_srv_settings.html
  source/app/blueprints/manage/templates/modal_add_user.html
  source/app/iris_engine/updater/updater.py
  source/app/models/models.py
  source/app/post_init.py
  source/app/schema/marshables.py
  source/app/static/assets/js/iris/manage_srv_settings.js
Labels: bug, enhancement

#115 Add data store
  docker/nginx/nginx.conf
  docker/webApp/Dockerfile
  docker/webApp/iris-entrypoint.sh
  source/app/blueprints/case/case_routes.py
  source/app/blueprints/case/case_timeline_routes.py
  source/app/blueprints/case/templates/case.html
  source/app/blueprints/case/templates/case_timeline.html
  source/app/blueprints/case/templates/modal_add_case_event.html
  source/app/blueprints/case/templates/modal_help_filter_tm.html
  source/app/blueprints/case/templates/modal_note_edit.html
  source/app/blueprints/datastore/__init__.py
  source/app/blueprints/datastore/datastore_routes.py
  source/app/blueprints/datastore/templates/modal_ds_file.html
  source/app/blueprints/datastore/templates/modal_ds_file_info.html
  source/app/blueprints/datastore/templates/modal_help_filter_ds.html
  source/app/blueprints/search/templates/search.html
  source/app/configuration.py
  source/app/datamgmt/datastore/__init__.py
  source/app/datamgmt/datastore/datastore_db.py
  source/app/datamgmt/reporter/report_db.py
  source/app/forms.py
  source/app/models/models.py
  source/app/schema/marshables.py
  source/app/static/assets/css/atlantis.css
  source/app/static/assets/css/dark-theme.css
  source/app/static/assets/img/loader.gif
  source/app/static/assets/js/atlantis.min.js
  source/app/static/assets/js/dark-mode.js
  source/app/static/assets/js/iris/case.asset.js
  source/app/static/assets/js/iris/case.ioc.js
  source/app/static/assets/js/iris/case.js
  source/app/static/assets/js/iris/case.notes.js
  source/app/static/assets/js/iris/case.rfiles.js
  source/app/static/assets/js/iris/case.summary.js
  source/app/static/assets/js/iris/case.tasks.js
  source/app/static/assets/js/iris/case.timeline.js
  source/app/static/assets/js/iris/common.js
  source/app/static/assets/js/iris/dashboard.js
  source/app/static/assets/js/iris/datastore.js
  source/app/static/assets/js/iris/dim_tasks.js
  source/app/static/assets/js/iris/manage_attributes.js
  source/app/templates/includes/datastore-sidebar.html
  source/app/templates/includes/footer.html
  source/app/templates/includes/footer_case.html
  source/app/templates/includes/header_case.html
  source/app/templates/includes/navigation.html
  source/app/templates/includes/navigation_ext.html
  source/app/templates/includes/quick-sidebar.html
  source/app/templates/layouts/default.html
  source/app/templates/layouts/default_ext.html
  source/app/util.py
  source/app/views.py
  source/requirements.txt
Labels: enhancement
