Repository dfir-iris/iris-web, pull requests merged in 2023-05, with the labels that each got.

#240 basic csv events file import (with default otions)
  .bumpversion.cfg
  .gitignore
  README.md
  docker-compose.yml
  source/app/blueprints/case/case_timeline_routes.py
  source/app/blueprints/case/templates/case_timeline.html
  source/app/blueprints/manage/manage_cases_routes.py
  source/app/configuration.py
  source/app/datamgmt/case/case_assets_db.py
  source/app/datamgmt/case/case_events_db.py
  source/app/datamgmt/case/case_iocs_db.py
  source/app/static/assets/js/iris/case.timeline.js
Labels: enhancement

#246 Some configuration checks when LDAP and automatic user creation are set
  source/app/configuration.py
Labels: enhancement

#248 Ensure database connectivity before trying to create tables
  source/app/post_init.py
Labels: bug, enhancement

#249 v2.2.0
  .gitignore
  source/app/blueprints/case/case_timeline_routes.py
  source/app/blueprints/case/templates/case.html
  source/app/blueprints/case/templates/case_timeline.html
  source/app/blueprints/manage/manage_alerts_status_routes.py
  source/app/blueprints/manage/manage_analysis_status_routes.py
  source/app/blueprints/manage/manage_assets_type_routes.py
  source/app/blueprints/manage/manage_case_classifications.py
  source/app/blueprints/manage/manage_event_categories_routes.py
  source/app/blueprints/manage/manage_ioc_types_routes.py
  source/app/blueprints/manage/manage_severities_routes.py
  source/app/configuration.py
  source/app/datamgmt/alerts/alerts_db.py
  source/app/datamgmt/case/case_assets_db.py
  source/app/datamgmt/case/case_events_db.py
  source/app/datamgmt/case/case_iocs_db.py
  source/app/datamgmt/manage/manage_case_classifications_db.py
  source/app/datamgmt/manage/manage_case_objs.py
  source/app/datamgmt/manage/manage_common.py
  source/app/post_init.py
  source/app/schema/marshables.py
  source/app/static/assets/js/iris/case.timeline.js
Labels: bug, enhancement

#247 Add newly created users after a LDAP authentication to group Analysts
  .env.model
  source/app/configuration.py
  source/app/datamgmt/manage/manage_groups_db.py
  source/app/iris_engine/access_control/ldap_handler.py
  source/app/post_init.py
Labels: enhancement

#254 v2.2.1
  .env.model
  docker/db/Dockerfile
  source/app/blueprints/alerts/alerts_routes.py
  source/app/blueprints/dim_tasks/dim_tasks.py
  source/app/blueprints/manage/manage_cases_routes.py
  source/app/blueprints/manage/templates/modal_case_info_from_case.html
  source/app/configuration.py
  source/app/datamgmt/alerts/alerts_db.py
  source/app/datamgmt/manage/manage_attribute_db.py
  source/app/datamgmt/manage/manage_cases_db.py
  source/app/datamgmt/manage/manage_groups_db.py
  source/app/iris_engine/access_control/ldap_handler.py
  source/app/post_init.py
  source/app/static/assets/js/iris/alerts.js
  source/app/static/assets/js/iris/case.tasks.js
  source/app/static/assets/js/iris/datastore.js
  source/app/static/assets/js/iris/manage.audit.cases.js
  source/app/static/assets/js/iris/manage.audit.users.js
Labels: bug

#253 Delete character escaping for passwords
  source/app/iris_engine/access_control/ldap_handler.py
Labels: enhancement

#259 Patches - v2.2.2
  source/app/blueprints/manage/manage_cases_routes.py
  source/app/datamgmt/alerts/alerts_db.py
  source/app/datamgmt/case/case_assets_db.py
  source/app/datamgmt/manage/manage_case_templates_db.py
  source/app/iris_engine/access_control/ldap_handler.py
  source/app/static/assets/js/iris/alerts.js
  source/app/util.py
Labels: bug, enhancement
