Repository dfir-iris/iris-web, pull requests merged in 2025-06, with the labels that each got.

#826 Api v2 update group
  source/app/blueprints/rest/manage/manage_groups.py
  source/app/blueprints/rest/v2/manage_routes/groups.py
  source/app/business/groups.py
  source/app/datamgmt/manage/manage_groups_db.py
  tests/tests_rest_groups.py
Labels: enhancement

#841 Database migration test
  .github/workflows/ci.yml
  docker-compose.base.yml
  docker-compose.dev.yml
  tests_database_migration/database_dumps/v2.4.14_empty.gz
  tests_database_migration/docker.py
  tests_database_migration/tests_database_migration.py
Labels: quality

#845 Fixed report generation is not filling case.for_customer variable
  docker-compose.dev.yml
  source/app/iris_engine/reporter/reporter.py
Labels: bug

#846 Issue680 for 2.5.0 beta.1
  source/app/iris_engine/reporter/reporter.py
  tests/data/report_templates/variable_case_for_customer_report_template.docx
  tests/requirements.txt
  tests/tests_rest_reports.py
Labels: bug
