Repository dfir-iris/iris-web, pull requests merged in 2025-05, with the labels that each got.

#802 Api v2 fixes
  source/app/blueprints/rest/alerts_routes.py
  source/app/blueprints/rest/v2/alerts.py
  source/app/business/alerts.py
  source/app/datamgmt/alerts/alerts_db.py
  tests/tests_rest_alerts.py
Labels: quality

#807 V2 api update alert
  source/app/blueprints/rest/alerts_routes.py
  source/app/blueprints/rest/v2/alerts.py
  source/app/business/alerts.py
  tests/tests_rest_alerts.py
Labels: enhancement

#808 Fixed IOC custom attributes not being displayed in IOC edition modal
  source/app/templates/modals/modal_attributes_nav.html
Labels: bug

#809 Issue758 for develop
  e2e/tests/administrator/case/ioc.spec.js
  source/app/datamgmt/manage/manage_attribute_db.py
  source/app/templates/modals/modal_attributes_nav.html
Labels: bug

#812 Added non regression end to end test for issue #798
  e2e/tests/administrator/manage/attributes.spec.js
Labels: bug

#815 Api v2 delete alert
  source/app/blueprints/rest/alerts_routes.py
  source/app/blueprints/rest/v2/alerts.py
  source/app/business/alerts.py
  source/app/datamgmt/alerts/alerts_db.py
  tests/iris.py
  tests/tests_rest_alerts.py
Labels: enhancement

#816 CSV upload of assets was calling a method which had been removed
  source/app/blueprints/rest/case/case_assets_routes.py
  source/app/schema/marshables.py
  tests/tests_rest_assets.py
Labels: bug

#817 Issue787 for develop
  .github/workflows/ci.yml
  source/app/blueprints/rest/case/case_assets_routes.py
  source/app/schema/marshables.py
  tests/tests_rest_alerts.py
  tests/tests_rest_assets.py
Labels: bug
